OPT=-g -O0
#OPT=-O2
CFLAGS=$(OPT)      \
	--std=c17  \
	-Wall      \
	$(PLATFORM_CFLAGS)
LDLIBS+=$(PLATFORM_LINK)
LDLIBS+=-lm

objs=main.o

all: main

main.o: main.c hdrpix.h

main: $(objs)

clean:
	rm -f main *.o
